-- ============================================================
-- FILE: 05_functions_cursors.sql
-- PROJECT: Inventory Management System
-- DESCRIPTION: PL/SQL Functions (Phase 5) + Cursors (Phase 6)
-- DATABASE: Oracle SQL Developer
-- RUN: F5 (Run Script)
-- ============================================================


-- ============================================================
-- PHASE 5: FUNCTIONS
-- ============================================================

-- ------------------------------------------------------------
-- FUNCTION 1: Calculate_Total_Price
-- Returns total price for a given product and quantity
-- Also validates product exists and is active
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION Calculate_Total_Price (
    p_product_id IN Products.ProductID%TYPE,
    p_quantity   IN NUMBER
)
RETURN NUMBER
AS
    v_unit_price  Products.Unit_Price%TYPE;
    v_prod_name   Products.Name%TYPE;
BEGIN
    -- Validate product and fetch price
    SELECT Unit_Price, Name
    INTO   v_unit_price, v_prod_name
    FROM   Products
    WHERE  ProductID = p_product_id
    AND    Is_Active = 1;

    RETURN ROUND(v_unit_price * p_quantity, 2);

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20010,
            'ERROR: Product ID ' || p_product_id ||
            ' not found or inactive.');
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20011,
            'ERROR in Calculate_Total_Price: ' || SQLERRM);
END Calculate_Total_Price;
/


-- ------------------------------------------------------------
-- FUNCTION 2: Get_Stock_Status
-- Returns stock status label for a product
-- Returns: 'LOW STOCK', 'OK', 'OUT OF STOCK', or 'NOT FOUND'
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION Get_Stock_Status (
    p_product_id IN Products.ProductID%TYPE
)
RETURN VARCHAR2
AS
    v_quantity      Stock_Management.Quantity%TYPE;
    v_restock_level Stock_Management.Restock_Level%TYPE;
BEGIN
    SELECT Quantity, Restock_Level
    INTO   v_quantity, v_restock_level
    FROM   Stock_Management
    WHERE  ProductID = p_product_id;

    IF v_quantity = 0 THEN
        RETURN 'OUT OF STOCK';
    ELSIF v_quantity < v_restock_level THEN
        RETURN 'LOW STOCK';
    ELSE
        RETURN 'OK';
    END IF;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 'NOT FOUND';
END Get_Stock_Status;
/


-- ------------------------------------------------------------
-- FUNCTION 3: Is_Category_Active
-- Returns 1 if category is active, 0 if inactive
-- Used internally by procedures and packages
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION Is_Category_Active (
    p_category_id IN Category.CategoryID%TYPE
)
RETURN NUMBER
AS
    v_is_active Category.IS_ACTIVE%TYPE;
BEGIN
    SELECT IS_ACTIVE
    INTO   v_is_active
    FROM   Category
    WHERE  CategoryID = p_category_id;

    RETURN v_is_active;

EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN -1;  -- Category does not exist
END Is_Category_Active;
/


-- ------------------------------------------------------------
-- FUNCTION 4: Get_Total_Sales_By_Product
-- Returns total revenue generated by a product across all sales
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION Get_Total_Sales_By_Product (
    p_product_id IN Products.ProductID%TYPE
)
RETURN NUMBER
AS
    v_total NUMBER(12,2) := 0;
BEGIN
    SELECT NVL(SUM(ti.Subtotal), 0)
    INTO   v_total
    FROM   Transaction_Items ti
    JOIN   Transactions      t  ON ti.TransactionID = t.TransactionID
    WHERE  ti.ProductID  = p_product_id
    AND    t.Trans_Type  = 'SALE';

    RETURN v_total;

EXCEPTION
    WHEN OTHERS THEN
        RETURN 0;
END Get_Total_Sales_By_Product;
/


-- ============================================================
-- VERIFY: All 4 functions compiled
-- ============================================================
SELECT Object_Name, Status
FROM   User_Objects
WHERE  Object_Type = 'FUNCTION'
AND    Object_Name IN (
    'CALCULATE_TOTAL_PRICE',
    'GET_STOCK_STATUS',
    'IS_CATEGORY_ACTIVE',
    'GET_TOTAL_SALES_BY_PRODUCT'
)
ORDER BY Object_Name;

-- Expected: 4 rows — all VALID


-- ============================================================
-- SAMPLE EXECUTIONS — FUNCTIONS
-- ============================================================
SET SERVEROUTPUT ON;

-- TEST 1: Calculate total price — 5x Wireless Mouse
DECLARE
    v_pid    NUMBER;
    v_result NUMBER;
BEGIN
    SELECT ProductID INTO v_pid FROM Products WHERE Name = 'Wireless Mouse';
    v_result := Calculate_Total_Price(v_pid, 5);
    DBMS_OUTPUT.PUT_LINE('Total Price (5x Wireless Mouse): Rs.' || v_result);
END;
/
-- Expected: Total Price (5x Wireless Mouse): Rs.2995

-- TEST 2: Calculate total price — 10x Ballpoint Pen Pack
DECLARE
    v_pid    NUMBER;
    v_result NUMBER;
BEGIN
    SELECT ProductID INTO v_pid FROM Products WHERE Name = 'Ballpoint Pen Pack';
    v_result := Calculate_Total_Price(v_pid, 10);
    DBMS_OUTPUT.PUT_LINE('Total Price (10x Ballpoint Pen Pack): Rs.' || v_result);
END;
/
-- Expected: Total Price (10x Ballpoint Pen Pack): Rs.450

-- TEST 3: Get stock status for all products using function in SELECT
SELECT p.Name                        AS Product,
       sm.Quantity,
       sm.Restock_Level,
       Get_Stock_Status(p.ProductID) AS Status
FROM   Products         p
JOIN   Stock_Management sm ON p.ProductID = sm.ProductID
ORDER BY p.Name;

-- Expected: each product shows OK / LOW STOCK / OUT OF STOCK

-- TEST 4: Check if categories are active using function
SELECT Name                              AS Category,
       IS_ACTIVE,
       Is_Category_Active(CategoryID)   AS Function_Result
FROM   Category
ORDER BY CategoryID;

-- Expected: 1 for active, 0 for inactive categories

-- TEST 5: Total sales revenue per product using function
SELECT p.Name                                   AS Product,
       Get_Total_Sales_By_Product(p.ProductID)  AS Total_Sales_Revenue
FROM   Products p
ORDER BY Total_Sales_Revenue DESC;

-- Expected: Wireless Mouse highest, unsold products show 0


-- ============================================================
-- PHASE 6: CURSORS
-- ============================================================

-- ------------------------------------------------------------
-- CURSOR 1: Explicit Cursor — Restocking Alert
-- Loops through all products needing restock
-- ONLY includes active categories (IS_ACTIVE = 1)
-- Core business rule enforced here
-- ------------------------------------------------------------
DECLARE
    -- Declare explicit cursor
    CURSOR c_restock_alert IS
        SELECT  p.ProductID,
                p.Name                              AS Product_Name,
                c.Name                              AS Category_Name,
                sm.Quantity                         AS Current_Stock,
                sm.Restock_Level,
                (sm.Restock_Level - sm.Quantity)    AS Units_Needed
        FROM    Products         p
        JOIN    Stock_Management sm ON p.ProductID  = sm.ProductID
        JOIN    Category         c  ON p.CategoryID = c.CategoryID
        WHERE   sm.Quantity  < sm.Restock_Level
        AND     c.IS_ACTIVE  = 1
        ORDER BY Units_Needed DESC;

    -- Record variable using cursor's row type
    v_rec c_restock_alert%ROWTYPE;
    v_count NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('==============================================');
    DBMS_OUTPUT.PUT_LINE('  RESTOCK ALERT — ACTIVE CATEGORIES ONLY');
    DBMS_OUTPUT.PUT_LINE('==============================================');
    DBMS_OUTPUT.PUT_LINE(
        RPAD('Product',           25) ||
        RPAD('Category',          15) ||
        RPAD('Stock',              8) ||
        RPAD('Restock Lvl',       13) ||
        'Units Needed'
    );
    DBMS_OUTPUT.PUT_LINE(RPAD('-', 70, '-'));

    -- Open, Fetch, Close pattern
    OPEN c_restock_alert;
    LOOP
        FETCH c_restock_alert INTO v_rec;
        EXIT WHEN c_restock_alert%NOTFOUND;

        v_count := v_count + 1;
        DBMS_OUTPUT.PUT_LINE(
            RPAD(v_rec.Product_Name,  25) ||
            RPAD(v_rec.Category_Name, 15) ||
            RPAD(v_rec.Current_Stock,  8) ||
            RPAD(v_rec.Restock_Level, 13) ||
            v_rec.Units_Needed
        );
    END LOOP;
    CLOSE c_restock_alert;

    DBMS_OUTPUT.PUT_LINE(RPAD('-', 70, '-'));
    DBMS_OUTPUT.PUT_LINE('Total products needing restock: ' || v_count);
    DBMS_OUTPUT.PUT_LINE('(Inactive category products excluded)');
END;
/
-- Expected output:
-- ==============================================
--   RESTOCK ALERT — ACTIVE CATEGORIES ONLY
-- ==============================================
-- Product                  Category       Stock   Restock Lvl  Units Needed
-- ----------------------------------------------------------------------
-- Ballpoint Pen Pack       Stationery     3       25           22
-- Wireless Mouse           Electronics    23      15           (after restock may change)
-- Bluetooth Headphones     Electronics    8       10           2


-- ------------------------------------------------------------
-- CURSOR 2: Cursor FOR LOOP — Full Stock Report
-- Simpler syntax using cursor FOR loop (implicit open/fetch/close)
-- Shows all products with stock status using Get_Stock_Status()
-- ------------------------------------------------------------
DECLARE
    CURSOR c_stock_report IS
        SELECT  p.ProductID,
                p.Name                              AS Product_Name,
                c.Name                              AS Category_Name,
                c.IS_ACTIVE,
                sm.Quantity,
                sm.Restock_Level
        FROM    Products         p
        JOIN    Category         c  ON p.CategoryID = c.CategoryID
        JOIN    Stock_Management sm ON p.ProductID  = sm.ProductID
        ORDER BY c.Name, p.Name;

BEGIN
    DBMS_OUTPUT.PUT_LINE('==============================================');
    DBMS_OUTPUT.PUT_LINE('        FULL STOCK REPORT');
    DBMS_OUTPUT.PUT_LINE('==============================================');

    -- Cursor FOR LOOP — no need to OPEN / FETCH / CLOSE manually
    FOR v_rec IN c_stock_report LOOP
        DBMS_OUTPUT.PUT_LINE(
            RPAD(v_rec.Product_Name,  25) ||
            RPAD(v_rec.Category_Name, 15) ||
            '  Qty: '    || RPAD(v_rec.Quantity,     5) ||
            '  Status: ' || Get_Stock_Status(v_rec.ProductID) ||
            CASE WHEN v_rec.IS_ACTIVE = 0
                 THEN ' [CATEGORY INACTIVE]'
                 ELSE ''
            END
        );
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('==============================================');
END;
/
-- Expected: 8 rows — each product with status label
-- Old CRT Monitor shows [CATEGORY INACTIVE]


-- ------------------------------------------------------------
-- CURSOR 3: Parameterized Cursor — Transactions by Type
-- Accepts a transaction type parameter
-- Loops and prints matching transactions
-- ------------------------------------------------------------
DECLARE
    -- Parameterized cursor
    CURSOR c_trans_by_type (p_type VARCHAR2) IS
        SELECT  t.TransactionID,
                u.Username,
                p.Name          AS Product_Name,
                ti.Quantity,
                ti.Unit_Price,
                ti.Subtotal,
                t.Trans_Date
        FROM    Transactions      t
        JOIN    Users             u  ON t.UserID       = u.UserID
        JOIN    Transaction_Items ti ON t.TransactionID = ti.TransactionID
        JOIN    Products          p  ON ti.ProductID   = p.ProductID
        WHERE   t.Trans_Type = p_type
        ORDER BY t.Trans_Date DESC;

    v_total_revenue NUMBER := 0;
BEGIN
    DBMS_OUTPUT.PUT_LINE('==============================================');
    DBMS_OUTPUT.PUT_LINE('   TRANSACTION REPORT — TYPE: SALE');
    DBMS_OUTPUT.PUT_LINE('==============================================');

    -- Open cursor with parameter 'SALE'
    FOR v_rec IN c_trans_by_type('SALE') LOOP
        DBMS_OUTPUT.PUT_LINE(
            'TxnID: '   || RPAD(v_rec.TransactionID, 5) ||
            'User: '    || RPAD(v_rec.Username,       15) ||
            'Product: ' || RPAD(v_rec.Product_Name,   22) ||
            'Qty: '     || RPAD(v_rec.Quantity,        5) ||
            'Subtotal: Rs.' || v_rec.Subtotal
        );
        v_total_revenue := v_total_revenue + NVL(v_rec.Subtotal, 0);
    END LOOP;

    DBMS_OUTPUT.PUT_LINE('----------------------------------------------');
    DBMS_OUTPUT.PUT_LINE('Total Sales Revenue: Rs.' || v_total_revenue);
END;
/
-- Expected: all SALE transactions with running total


-- ------------------------------------------------------------
-- CURSOR 4: Cursor with UPDATE — Auto Restock Alert Logger
-- Loops through low-stock active-category products
-- Inserts a STOCK_ALERT report entry for each
-- ------------------------------------------------------------
DECLARE
    CURSOR c_low_stock IS
        SELECT  p.ProductID,
                p.Name                           AS Product_Name,
                c.Name                           AS Category_Name,
                sm.Quantity,
                sm.Restock_Level,
                (sm.Restock_Level - sm.Quantity) AS Units_Needed
        FROM    Products         p
        JOIN    Stock_Management sm ON p.ProductID  = sm.ProductID
        JOIN    Category         c  ON p.CategoryID = c.CategoryID
        WHERE   sm.Quantity  < sm.Restock_Level
        AND     c.IS_ACTIVE  = 1;

    v_report_by  NUMBER;
    v_count      NUMBER := 0;
BEGIN
    -- Get admin user ID
    SELECT UserID INTO v_report_by
    FROM   Users WHERE Username = 'admin_raj';

    FOR v_rec IN c_low_stock LOOP
        v_count := v_count + 1;

        -- Insert one report entry per low-stock product
        INSERT INTO Reports (
            ReportID, Report_Type, Generated_By, Report_Data
        )
        VALUES (
            seq_reports.NEXTVAL,
            'STOCK_ALERT',
            v_report_by,
            'Product: '    || v_rec.Product_Name  ||
            ' | Category: '|| v_rec.Category_Name ||
            ' | Stock: '   || v_rec.Quantity       ||
            ' | Needed: '  || v_rec.Units_Needed
        );

        DBMS_OUTPUT.PUT_LINE(
            'Alert logged: ' || v_rec.Product_Name ||
            ' needs ' || v_rec.Units_Needed || ' units.'
        );
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Total alerts logged: ' || v_count);
END;
/
-- Expected:
-- Alert logged: Ballpoint Pen Pack needs 22 units.
-- Alert logged: Bluetooth Headphones needs 2 units.
-- Total alerts logged: 2  (Wireless Mouse restocked earlier — may be OK now)


-- ------------------------------------------------------------
-- VERIFY: Reports table populated by cursor
-- ------------------------------------------------------------
SELECT ReportID, Report_Type, Generated_At, Report_Data
FROM   Reports
ORDER BY ReportID;

-- Expected: rows with STOCK_ALERT type and product details
