spring.application.name=ims

# Server Connection
server.port=8080

# Oracle Database Connection
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=system
spring.datasource.password=RedHaati48
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Just to keep the logs clean
spring.main.banner-mode=off